### ISSUE TITLE
Reproducing results from HeSBO-BM 

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [aminnayebi/HesBO#3]
Hi Amin,

I wanted to reproduce the results you have in the Figure 1 of your paper for the HeSBO-BM for the Rosenbrock or Branin function and use the below command:

python blossom_run.py Rosenbrock 100 4 100 1 1

First I wanted to ask if the above command is correct. 

What I was mainly confused however was because of the lack of document the from the gpbo package for the csv file that it saves:

I was not sure which one of the columns represents the "Function Value" or observation at each evaluation or best-solution at a given evaluation. My guess only is "truey at xrecc" column or "y" however so far.

Finally, I just wanted to check with you if it is correct to use the "back_projection" function to map the 4 dimensional x_optimum we find from the csv file to the 100 dimensional original space?

Thanks.
Alireza

**Comment by aminnayebi** [comment]
Hi Alireza,

1- The command that you wrote above for reproducing the results is correct. 
2- I agree that their documentation for saved csv file is not enough, however from the name of each column, you can grasp some information. I used the column "truey at xrecc" which shows the value of the function at the recommended point at each step. There is a slight difference between observed points and recommended points in each step. For further information read [HERE](https://github.com/wujian16/Cornell-MOE#correct-performance-evaluation-with-knowledge-gradient-acquisition-functions).
3- You can map the points using "back_projection" function. Note that the values of "high_to_low" and "sign" variables that you will pass to the back_projection function, must be the same as those values when you run the model.

**Comment by a-z-e-r-i-l-a** [comment]
Thank you for your answers. 

If I understood correctly then, "truey at xrecc" is the true observation which the oracle gave us at a recommended input x ( where this recommendation is from optimizing an acquisition function).

**Comment by aminnayebi** [comment]
Yes, that is correct.
