### ISSUE TITLE
A few questions...

### ISSUE THREAD

**Issue by ben-arnao** [aminnayebi/HesBO#4]
I am looking more into a solution to enable Bayesian Optimization for a high dimensional problem like neural network tuning. Seems like most of the solutions involve some sort of embedding space.

I have a few novice questions I was hoping I could get some help with.

Do you need knowledge of the "intrinsic" dimensionality of your problem for a method like this to work? Do any of these methods figure out for themselves how to embed your parameter space?

How do you know if your problem is embeddable? You have different parameters for your function for a reason. Is it possible something like NN tuning cannot be helped with a method like this if the true dimensionality of the problem is the amount of parameters you are tuning?

**Comment by aminnayebi** [comment]
Sorry if I'm responding very late, I didn't see your issue.
1- You don't need to know what is the intrinsic dimensionality exactly. But you need to pick a number for it. You can try a couple of numbers and see which one would be best.
2- If you read our paper, only HeSBO and Rembo need to know the number of intrinsic dimensionalities, but others like BOCK, EBO, SKL, and ADD don't need that.
3- Generally speaking, all the problems are somehow embedded. For example, for parameter tuning, not all the parameters have significant effect on the outcome, so we can assume that only some of the parameters are important. In this way, you are assuming that you have some true dimensionalities which are fewer than all the parameters.
